openapi: 3.0.3
info:
  title: User Management API
  version: 1.0.0
paths:
  /users:
    get:
      summary: Get list of users
      parameters:
        - name: page
          in: query
          required: true
          schema:
            type: integer
          description: Page number
        - name: size
          in: query
          required: true
          schema:
            type: integer
          description: Number of users per page
      responses:
        '200':
          description: List of users found
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                    name:
                      type: string
                    email:
                      type: string
              example:
                - id: 1
                  name: Alice
                  email: alice@example.com
                - id: 2
                  name: Bob
                  email: bob@example.com
        '400':
          description: Bad request due to wrong parameter types
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
              example:
                error: "Bad types for provided query parameters"
